/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { MNFT } from "./MNFT";
export type { Market } from "./Market";
export type { MaterialNFT } from "./MaterialNFT";
export type { Xpc } from "./Xpc";
